modLoader = "javafml"
loaderVersion = "[46.0.0,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "thematic_api"
version = "${version}"
displayName = "Thematic API"
authors = "awitkowski0"
description = '''
A modern Minecraft player animation library
'''
#logoFile = ""

[[dependencies.thematic_api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
